# Generated by Django 5.2.3 on 2026-04-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_participant_login_code_pin_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysession',
            name='rcq_score',
            field=models.JSONField(blank=True, help_text='Hidden scoring for RCQ (correctness and points)', null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='condition',
            field=models.CharField(choices=[('personalized', 'Personalized'), ('generic', 'Generic')], max_length=20),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='status',
            field=models.CharField(choices=[('locked', 'Locked'), ('available', 'Available'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='locked', max_length=20),
        ),
    ]
