# Generated by Django 5.2.3 on 2026-04-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_studysession_rcq_score_alter_participant_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysession',
            name='caiq_panas_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studysession',
            name='caiq_panas_responses',
            field=models.JSONField(blank=True, help_text='CAIQ-PANAS survey responses with metadata', null=True),
        ),
    ]
