# Generated by Django 5.2.3 on 2026-04-28 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_studysession_caiq_panas_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysession',
            name='caiq_panas_scores',
            field=models.JSONField(blank=True, help_text='Hidden CAIQ-PANAS scores (CAIQ, PANAS positive, PANAS negative, overall affect)', null=True),
        ),
    ]
